#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul  3 12:04:42 2019

@author: Ben
"""
'''
TODO: 1) Create a way for bots to play each other
2) Create a bot that takes in the inputs:
    Current Hole Cards
    Current Table Cards
    Pot
    Players left
    Current Raise
And returns an action:
    Call
    Raise (by how much)
    Fold

3) Need an evaluation (money made for each n rounds)
4) Create a population
5) Should be using a neural net to convert input into output (TFLearn)
'''